limabia/doei

app/assets/stylesheets/default.scss, app/controllers/default_controller.rb, app/helpers/default_helper.rb, app/views/default/index.html, config/routes.rb, spec/helpers/default_helper_spec.rb, spec/requests/default_request_spec.rb
Primeiros passos com o Rails. Criando uma página default para entender o route.
=> Adicionando um página default para teste de routes.

app/controllers/produtos_controller.rb, app/views/default/index.html, app/views/layouts/application.html.erb, app/views/produtos/new.html.erb, app/views/produtos/show.html.erb, config/routes.rb
tag invalida no html da pagina application.
=> pagina application remover tag errada no html.

app/controllers/produtos_controller.rb, app/views/layouts/_header.html.erb, app/views/produtos/busca.html.erb, config/routes.rb
Depois do "trauma" em fazer muitas mudanças e não passar nos testes, vou fazer PRs para pequenas mudanças! Fic amais fácil, ao menos para mim, de administrá-las!
=> Atualizando a busca aos poucos. Funciona, mas não tem estética.

README.md
PR criado só para manter a ordem. Nenhuma funcionalidade, apenas seguindo as instruções do monitor.
=> Seguindo as instruções do monitor quanto ao nome e gits dos integrantes.

app/views/layouts/_header.html.erb, app/views/produtos/busca.html.erb, app/views/produtos/index.html.erb, app/views/produtos/new.html.erb
Melhorando a aparência das páginas com o bootstrap.
=> Consertando o CSS da exibição dos produtos.

app/views/usuarios/index.html.erb
=> Exibe apenas o usuario conectado na sessao.

app/controllers/sessoes_controller.rb
=> Ajuste no logon para redirecionar para home.

app/models/usuario.rb, app/views/usuarios/new.html.erb
Ajuste no redirecionamento do botão voltar, dentro da tela 'cadastro novo usuário' para home.
=> Ajuste redirecionamento cadastro de novo usuario.

app/views/usuarios/index.html.erb
Adicionando a navbar na página de usuários.
=> Inserindo a navbar na página de usuários.

app/views/sessoes/busca.html.erb
Organizando melhor a exibição com os cards.
=> Colocando o resultado das buscas em cards do bootstrap.

app/views/layouts/_header.html.erb, app/views/produtos/index.html.erb, app/views/produtos/show.html.erb, config/routes.rb, features/step_definitions/produtos_cadastrar_step.rb
A página está funcional. Ainda precisa de ajustes!
=> Adicionando página de produto

features/foto_produto.feature
Pull request criado para centralizar as entregas da feature: Foto de produto na listagem.
Aceitar somente, após a revisão no pivotal e código.
=> Feature: Foto de produto na listagem.

features/foto_produto.feature, features/step_definitions/produtos_cadastrar_step.rb
Não aprovar essa PR, até que toda a feature esteja pronta. Assim que finalizar vou informar que a revisão pode ser iniciada.
=> Feature: Página de produto com a foto do item

features/step_definitions/produtos_cadastrar_step.rb
…, pois agora e obrigatorio o upload de imagem.
=> Cenário de teste (Cadastro de produto): ajustado para suportar o campo upload imagem

features/detalhes_produto.feature, features/step_definitions/home_step.rb
Criei os testes de integração para o detalhes do produto.
=> Teste de integração com o Cucumber para o Detalhes do produto.

app/controllers/produtos_controller.rb, app/views/produtos/edit.html.erb, app/views/produtos/show.html.erb, config/routes.rb, features/editar_produto.feature
Depois vou criar o teste de unidade.
=> Adicionando funcionalidade de editar produto e testes de integração.

spec/controllers/produtos_controller_spec.rb, spec/models/produto_spec.rb
Incluindo os testes de unidade para editar produto.
=> Testes de unidade para a edição de produtos

app/controllers/produtos_controller.rb, features/editar_produto.feature
Está ficando baixa a cobertura de testes do Travis. Inseri alguns de integração para ajudar. Pretendo colocar mais de unidade.
=> Adicionando testes para melhor a cobertura

spec/controllers/produtos_controller_spec.rb
Coloquei três testes novos de unidade. Acredito que ajudará a melhorar a cobertura do Travis.
=> Inserindo testes de unidade para tentar melhorar cobertura

app/assets/stylesheets/application.css, app/views/layouts/_footer.html.erb, app/views/produtos/meus_produtos.html.erb
Parecia que não tinha mais a opção de editar, mas era o rodapé que estava tampando os cards mais abaixo e o botão de editar para produtos com foto. Além disso, arrumei a disposição dos cards e o linf "Detalhes" no "Meus Produtos".
=> Tornando visível a opção de editar

app/controllers/produtos_controller.rb, app/views/produtos/edit.html.erb, app/views/produtos/show.html.erb, db/migrate/20201114003941_produtos.rb, db/schema.rb, features/editar_produto.feature, features/step_definitions/produtos_cadastrar_step.rb, spec/controllers/produtos_controller_spec.rb
Feature criado com BDD e TDD. Como foi um campo novo criado, não foi preciso adicionar nada no controller, mesmo assim tem testes novos. Além disso, eu mexi nos botões "Quero resgatar", "Editar" e "Remover", agora quem cadastrou só vê os dois últimos. "Quero resgatar" é só para quem não é o dono do produto.
Na minha máquina, Rspec e Cucumber não falharam!
=> Função que altera o status "Já doado" do produto de "Não" para "Sim".

app/views/produtos/meus_produtos.html.erb
Não há testes pois não foi criado nenhum método novo nos controllers e a disposição visual é a mesma.
=> Dividindo a listagem de produtos entre disponíveis e doados

db/migrate/20201114133945_change_situacao.rb
Ajuste na entrega do Renato, coluna o rename da coluna situaçao para condiçao, estava incorreto.
=> Ajuste na entrega Renato

db/migrate/20201114201101_change_feedbacks_curtiu.rb, db/migrate/20201114201153_change_feedbacks_nao_curtiu.rb, db/schema.rb
Ajuste na entrega do Renato, coluna o rename da coluna situaçao para condiçao, estava incorreto. No heroku nao houve atualizacao.
=> Ajuste na entrega do Renato com Heroku.

app/controllers/feedbacks_controller.rb
=> Refatoraçao na controller feedback para considerar coluna nula.

app/controllers/feedbacks_controller.rb
=> Migrate atualizaçao feedback

app/views/produtos/index.html.erb, features/editar_produto.feature, features/step_definitions/produtos_cadastrar_step.rb
Não tem sentido exibir produtos já doados. Era para eu ter feito isso na outra PR.
=> Exibindo apenas os produtos disponíveis
